<?php
/**
 * @file
 *  Provides functionality to save Rules configurations as CMI files.
 */

/**
 * Implements hook_entity_info_alter().
 */
function rules_cmi_entity_info_alter(&$info) {
  $info['rules_config']['entity class'] = 'EntityPlusCmiEntity';
  $info['rules_config']['controller class'] = 'RulesEntityCmiController';
  $info['rules_config']['views controller'] = FALSE;
  // Does nothing until Entity Plus issue #175 is merged.
  $info['rules_config']['cmi storage'] = TRUE;
  // We must "fool" Rules plugins by assigning 'schema_fields_sql' info to the entity.
  $info['rules_config']['schema_fields_sql']['base table'] = backdrop_schema_fields_sql('rules_config');
}

/**
 * Implements hook_autoload_info().
 */
function rules_cmi_autoload_info() {
  return array(
    'RulesEntityCmiController' => 'includes/RulesEntityCmiController.inc',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rules_cmi_form_rules_admin_reaction_overview_alter(&$form, &$form_state) {
  $form['filter']['tag']['#options'] = array(0 => t('<All>')) + rules_cmi_get_tags();
  // Add the operation "CMI export"
  // This is complicated and pretty ridiculous. Rules doesn't allow to set a
  // different UI controller other than RulesUIController, as defined in
  // function rules_ui(). Therefore we have to do a lot of juggling to modify
  // the operations.
  $statuses = array('active', 'inactive');
  foreach ($statuses as $status) {
    foreach (element_children($form[$status]['#rows']) as $index) {
      $machine_name = $form[$status]['#rows'][$index][0]['data']['description']['settings']['machine_name']['#markup'];
      $to_remove = t('Machine name') . ': ';
      $machine_name = str_replace($to_remove, '', $machine_name);
      $form[$status]['#rows'][$index]['operations']['data']['#links']['cmi_export'] = array(
        'title' => t('CMI Export'),
        'href' => 'admin/config/development/configuration/single/export', 
        'query' => array(
          'group' => 'Rules configuration',
          'name' => 'rules_config.' . $machine_name,
        ),
        'attributes' => array(
          'class' => array(
              'edit',
              'action',
          ),
        ),
      );
    }
  }
}

/**
 * Get tags from reaction rules.
 * 
 * Since tags are not stored in DB anymore, these have to be retrieved from the
 * cmi records.
 * 
 * @return array
 *  An array of tags keyed by tag name.
 */
function rules_cmi_get_tags() {
  $rules_configs = rules_config_load_multiple(FALSE);
  $tags = array();
  foreach ($rules_configs as $rules_config) {
    foreach ($rules_config->tags as $tag) {
      $tags[$tag] = $tag;
    }
  }
  return $tags;
}
